using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TB.Chatbot.Domain.Entities
{
    [Table("web_order_motor_premiums")]
    public class WebOrderMotorPremiums
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        public string? quo_number { get; set; }
        public int? premiums_id { get; set; }
        public string? company_code { get; set; }
        public string? TM_PRODUCT_CODE { get; set; }
        public string? TM_PRODUCT_DST_GROUP { get; set; }
        public string? TM_PRODUCT_CODE_OIC { get; set; }
        public string? title_masterplan { get; set; }
        public string? en_title_masterplan { get; set; }
        public string? coverage_code { get; set; }
        public string? group_agent { get; set; }
        public string? repair_type { get; set; }
        public string? car_brand { get; set; }
        public string? car_model { get; set; }
        public string? car_sub_model { get; set; }
        public string? car_group { get; set; }
        public string? car_year { get; set; }
        public string? car_engine_size { get; set; }
        public string? sum_insure { get; set; }
        public string? sum_insure_default { get; set; }
        public string? driver_flag { get; set; }
        public string? driver_year_of_birth { get; set; }
        public string? driver_ranges_year_of_birth { get; set; }
        public string? accessory_flag { get; set; }
        public string? accessory_des { get; set; }
        public string? effective_date { get; set; }
        public string? expire_date { get; set; }
        public string? subclass_sos { get; set; }
        public string? subclass_gis { get; set; }
        public string? f_t { get; set; }
        public string? atm_type { get; set; }
        public string? atm_type_txt { get; set; }
        public string? active_year { get; set; }
        public string? active_type { get; set; }
        public string? s_p { get; set; }
        public string? net_premiums { get; set; }
        public string? stamp { get; set; }
        public string? tax { get; set; }
        public string? total_premiums { get; set; }
        public string? cmi_net_premiums { get; set; }
        public string? cmi_stamp { get; set; }
        public string? cmi_tax { get; set; }
        public string? cmi_total_premiums { get; set; }
        public string? total_premiums_with_cmi { get; set; }
        public string? status { get; set; }
        public string? cover_txt1 { get; set; }
        public string? cover_txt2 { get; set; }
        public string? cover_txt3 { get; set; }
        public string? cover_txt4 { get; set; }
        public string? cover_txt5 { get; set; }
        public string? cover_txt6 { get; set; }
        public string? cover_txt7 { get; set; }
        public string? cover_txt8 { get; set; }
        public string? cover_txt9 { get; set; }
        public string? cover_txt10 { get; set; }
        public string? cover_txt11 { get; set; }
        public string? cover_txt12 { get; set; }
        public string? cover_txt13 { get; set; }
        public string? cover_txt14 { get; set; }
        public string? cover_txt15 { get; set; }
        public string? cover_txt16 { get; set; }
        public string? cover_txt17 { get; set; }
        public string? cover_txt18 { get; set; }
        public string? cover_txt19 { get; set; }
        public string? cover_txt20 { get; set; }
        public string? en_cover_txt1 { get; set; }
        public string? en_cover_txt2 { get; set; }
        public string? en_cover_txt3 { get; set; }
        public string? en_cover_txt4 { get; set; }
        public string? en_cover_txt5 { get; set; }
        public string? en_cover_txt6 { get; set; }
        public string? en_cover_txt7 { get; set; }
        public string? en_cover_txt8 { get; set; }
        public string? en_cover_txt9 { get; set; }
        public string? en_cover_txt10 { get; set; }
        public string? en_cover_txt11 { get; set; }
        public string? en_cover_txt12 { get; set; }
        public string? en_cover_txt13 { get; set; }
        public string? en_cover_txt14 { get; set; }
        public string? en_cover_txt15 { get; set; }
        public string? en_cover_txt16 { get; set; }
        public string? en_cover_txt17 { get; set; }
        public string? en_cover_txt18 { get; set; }
        public string? en_cover_txt19 { get; set; }
        public string? en_cover_txt20 { get; set; }
        public string? cover_val1 { get; set; }
        public string? cover_val2 { get; set; }
        public string? cover_val3 { get; set; }
        public string? cover_val4 { get; set; }
        public string? cover_val5 { get; set; }
        public string? cover_val6 { get; set; }
        public string? cover_val7 { get; set; }
        public string? cover_val8 { get; set; }
        public string? cover_val9 { get; set; }
        public string? cover_val10 { get; set; }
        public string? cover_val11 { get; set; }
        public string? cover_val12 { get; set; }
        public string? cover_val13 { get; set; }
        public string? cover_val14 { get; set; }
        public string? cover_val15 { get; set; }
        public string? cover_val16 { get; set; }
        public string? cover_val17 { get; set; }
        public string? cover_val18 { get; set; }
        public string? cover_val19 { get; set; }
        public string? cover_val20 { get; set; }
        public string? en_cover_val1 { get; set; }
        public string? en_cover_val2 { get; set; }
        public string? en_cover_val3 { get; set; }
        public string? en_cover_val4 { get; set; }
        public string? en_cover_val5 { get; set; }
        public string? en_cover_val6 { get; set; }
        public string? en_cover_val7 { get; set; }
        public string? en_cover_val8 { get; set; }
        public string? en_cover_val9 { get; set; }
        public string? en_cover_val10 { get; set; }
        public string? en_cover_val11 { get; set; }
        public string? en_cover_val12 { get; set; }
        public string? en_cover_val13 { get; set; }
        public string? en_cover_val14 { get; set; }
        public string? en_cover_val15 { get; set; }
        public string? en_cover_val16 { get; set; }
        public string? en_cover_val17 { get; set; }
        public string? en_cover_val18 { get; set; }
        public string? en_cover_val19 { get; set; }
        public string? en_cover_val20 { get; set; }
        public string? status_system { get; set; }
        public string? sub_insure { get; set; }
        public string? net_comm { get; set; }
        public string? cmi_net_comm { get; set; }
        public string? comm_percent { get; set; }
        public string? comm_percent_tax { get; set; }
        public string? total_comm { get; set; }
        public string? delivery_amount { get; set; }
        public string? cmi_comm_percent { get; set; }
        public string? cmi_comm_percent_tax { get; set; }
        public string? cmi_total_comm { get; set; }
        public string? cmi_delivery_amount { get; set; }
        public string? od { get; set; }
    }
}