using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace TB.Chatbot.Domain.Entities
{
    [Table("web_product_cover_txt")]
    public class WebProductCoverTxt
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }

        public int lastcreate { get; set; }
        public int lastupdate { get; set; }
        public string? lastcreate_s { get; set; }
        public string? lastupdate_s { get; set; }
        public int sort { get; set; }
        public int status { get; set; }
        public int pb_status { get; set; }
        public string? last_user { get; set; }
        public string? pb_last_user { get; set; }
        public int show_front { get; set; }
        public string? title { get; set; }
        public string? en_title { get; set; }

        [JsonPropertyName("tm_product_dst_group")]
        public string? TM_PRODUCT_DST_GROUP { get; set; }

        public string? cover_txt1 { get; set; }
        public string? cover_txt2 { get; set; }
        public string? cover_txt3 { get; set; }
        public string? cover_txt4 { get; set; }
        public string? cover_txt5 { get; set; }
        public string? cover_txt6 { get; set; }
        public string? cover_txt7 { get; set; }
        public string? cover_txt8 { get; set; }
        public string? cover_txt9 { get; set; }
        public string? cover_txt10 { get; set; }
        public string? cover_txt11 { get; set; }
        public string? cover_txt12 { get; set; }
        public string? cover_txt13 { get; set; }
        public string? cover_txt14 { get; set; }
        public string? cover_txt15 { get; set; }
        public string? cover_txt16 { get; set; }
        public string? cover_txt17 { get; set; }
        public string? cover_txt18 { get; set; }
        public string? cover_txt19 { get; set; }
        public string? cover_txt20 { get; set; }
        public string? en_cover_txt1 { get; set; }
        public string? en_cover_txt2 { get; set; }
        public string? en_cover_txt3 { get; set; }
        public string? en_cover_txt4 { get; set; }
        public string? en_cover_txt5 { get; set; }
        public string? en_cover_txt6 { get; set; }
        public string? en_cover_txt7 { get; set; }
        public string? en_cover_txt8 { get; set; }
        public string? en_cover_txt9 { get; set; }
        public string? en_cover_txt10 { get; set; }
        public string? en_cover_txt11 { get; set; }
        public string? en_cover_txt12 { get; set; }
        public string? en_cover_txt13 { get; set; }
        public string? en_cover_txt14 { get; set; }
        public string? en_cover_txt15 { get; set; }
        public string? en_cover_txt16 { get; set; }
        public string? en_cover_txt17 { get; set; }
        public string? en_cover_txt18 { get; set; }
        public string? en_cover_txt19 { get; set; }
        public string? en_cover_txt20 { get; set; }
        public string? pb_title { get; set; }
        public string? pb_en_title { get; set; }
        public string? pb_TM_PRODUCT_DST_GROUP { get; set; }
        public string? pb_cover_txt1 { get; set; }
        public string? pb_cover_txt2 { get; set; }
        public string? pb_cover_txt3 { get; set; }
        public string? pb_cover_txt4 { get; set; }
        public string? pb_cover_txt5 { get; set; }
        public string? pb_cover_txt6 { get; set; }
        public string? pb_cover_txt7 { get; set; }
        public string? pb_cover_txt8 { get; set; }
        public string? pb_cover_txt9 { get; set; }
        public string? pb_cover_txt10 { get; set; }
        public string? pb_cover_txt11 { get; set; }
        public string? pb_cover_txt12 { get; set; }
        public string? pb_cover_txt13 { get; set; }
        public string? pb_cover_txt14 { get; set; }
        public string? pb_cover_txt15 { get; set; }
        public string? pb_cover_txt16 { get; set; }
        public string? pb_cover_txt17 { get; set; }
        public string? pb_cover_txt18 { get; set; }
        public string? pb_cover_txt19 { get; set; }
        public string? pb_cover_txt20 { get; set; }
        public string? pb_en_cover_txt1 { get; set; }
        public string? pb_en_cover_txt2 { get; set; }
        public string? pb_en_cover_txt3 { get; set; }
        public string? pb_en_cover_txt4 { get; set; }
        public string? pb_en_cover_txt5 { get; set; }
        public string? pb_en_cover_txt6 { get; set; }
        public string? pb_en_cover_txt7 { get; set; }
        public string? pb_en_cover_txt8 { get; set; }
        public string? pb_en_cover_txt9 { get; set; }
        public string? pb_en_cover_txt10 { get; set; }
        public string? pb_en_cover_txt11 { get; set; }
        public string? pb_en_cover_txt12 { get; set; }
        public string? pb_en_cover_txt13 { get; set; }
        public string? pb_en_cover_txt14 { get; set; }
        public string? pb_en_cover_txt15 { get; set; }
        public string? pb_en_cover_txt16 { get; set; }
        public string? pb_en_cover_txt17 { get; set; }
        public string? pb_en_cover_txt18 { get; set; }
        public string? pb_en_cover_txt19 { get; set; }
        public string? pb_en_cover_txt20 { get; set; }
        public string? coverage_code { get; set; }
        public string? pb_coverage_code { get; set; }
        public string? cover1_renew_mapping_type { get; set; }
        public string? cover1_renew_field { get; set; }
        public string? cover1_renew_custom_cover { get; set; }
        public string? cover1_en_renew_custom_cover { get; set; }
        public string? cover2_renew_mapping_type { get; set; }
        public string? cover2_renew_field { get; set; }
        public string? cover2_renew_custom_cover { get; set; }
        public string? cover2_en_renew_custom_cover { get; set; }
        public string? cover3_renew_mapping_type { get; set; }
        public string? cover3_renew_field { get; set; }
        public string? cover3_renew_custom_cover { get; set; }
        public string? cover3_en_renew_custom_cover { get; set; }
        public string? cover4_renew_mapping_type { get; set; }
        public string? cover4_renew_field { get; set; }
        public string? cover4_renew_custom_cover { get; set; }
        public string? cover4_en_renew_custom_cover { get; set; }
        public string? cover5_renew_mapping_type { get; set; }
        public string? cover5_renew_field { get; set; }
        public string? cover5_renew_custom_cover { get; set; }
        public string? cover5_en_renew_custom_cover { get; set; }
        public string? cover6_renew_mapping_type { get; set; }
        public string? cover6_renew_field { get; set; }
        public string? cover6_renew_custom_cover { get; set; }
        public string? cover6_en_renew_custom_cover { get; set; }
        public string? cover7_renew_mapping_type { get; set; }
        public string? cover7_renew_field { get; set; }
        public string? cover7_renew_custom_cover { get; set; }
        public string? cover7_en_renew_custom_cover { get; set; }
        public string? cover8_renew_mapping_type { get; set; }
        public string? cover8_renew_field { get; set; }
        public string? cover8_renew_custom_cover { get; set; }
        public string? cover8_en_renew_custom_cover { get; set; }
        public string? cover9_renew_mapping_type { get; set; }
        public string? cover9_renew_field { get; set; }
        public string? cover9_renew_custom_cover { get; set; }
        public string? cover9_en_renew_custom_cover { get; set; }
        public string? cover10_renew_mapping_type { get; set; }
        public string? cover10_renew_field { get; set; }
        public string? cover10_renew_custom_cover { get; set; }
        public string? cover10_en_renew_custom_cover { get; set; }
        public string? cover11_renew_mapping_type { get; set; }
        public string? cover11_renew_field { get; set; }
        public string? cover11_renew_custom_cover { get; set; }
        public string? cover11_en_renew_custom_cover { get; set; }
        public string? cover12_renew_mapping_type { get; set; }
        public string? cover12_renew_field { get; set; }
        public string? cover12_renew_custom_cover { get; set; }
        public string? cover12_en_renew_custom_cover { get; set; }
        public string? cover13_renew_mapping_type { get; set; }
        public string? cover13_renew_field { get; set; }
        public string? cover13_renew_custom_cover { get; set; }
        public string? cover13_en_renew_custom_cover { get; set; }
        public string? cover14_renew_mapping_type { get; set; }
        public string? cover14_renew_field { get; set; }
        public string? cover14_renew_custom_cover { get; set; }
        public string? cover14_en_renew_custom_cover { get; set; }
        public string? cover15_renew_mapping_type { get; set; }
        public string? cover15_renew_field { get; set; }
        public string? cover15_renew_custom_cover { get; set; }
        public string? cover15_en_renew_custom_cover { get; set; }
        public string? cover16_renew_mapping_type { get; set; }
        public string? cover16_renew_field { get; set; }
        public string? cover16_renew_custom_cover { get; set; }
        public string? cover16_en_renew_custom_cover { get; set; }
        public string? cover17_renew_mapping_type { get; set; }
        public string? cover17_renew_field { get; set; }
        public string? cover17_renew_custom_cover { get; set; }
        public string? cover17_en_renew_custom_cover { get; set; }
        public string? cover18_renew_mapping_type { get; set; }
        public string? cover18_renew_field { get; set; }
        public string? cover18_renew_custom_cover { get; set; }
        public string? cover18_en_renew_custom_cover { get; set; }
        public string? cover19_renew_mapping_type { get; set; }
        public string? cover19_renew_field { get; set; }
        public string? cover19_renew_custom_cover { get; set; }
        public string? cover19_en_renew_custom_cover { get; set; }
        public string? cover20_renew_mapping_type { get; set; }
        public string? cover20_renew_field { get; set; }
        public string? cover20_renew_custom_cover { get; set; }
        public string? cover20_en_renew_custom_cover { get; set; }
        public string? pb_cover1_renew_mapping_type { get; set; }
        public string? pb_cover1_renew_field { get; set; }
        public string? pb_cover1_renew_custom_cover { get; set; }
        public string? pb_cover1_en_renew_custom_cover { get; set; }
        public string? pb_cover2_renew_mapping_type { get; set; }
        public string? pb_cover2_renew_field { get; set; }
        public string? pb_cover2_renew_custom_cover { get; set; }
        public string? pb_cover2_en_renew_custom_cover { get; set; }
        public string? pb_cover3_renew_mapping_type { get; set; }
        public string? pb_cover3_renew_field { get; set; }
        public string? pb_cover3_renew_custom_cover { get; set; }
        public string? pb_cover3_en_renew_custom_cover { get; set; }
        public string? pb_cover4_renew_mapping_type { get; set; }
        public string? pb_cover4_renew_field { get; set; }
        public string? pb_cover4_renew_custom_cover { get; set; }
        public string? pb_cover4_en_renew_custom_cover { get; set; }
        public string? pb_cover5_renew_mapping_type { get; set; }
        public string? pb_cover5_renew_field { get; set; }
        public string? pb_cover5_renew_custom_cover { get; set; }
        public string? pb_cover5_en_renew_custom_cover { get; set; }
        public string? pb_cover6_renew_mapping_type { get; set; }
        public string? pb_cover6_renew_field { get; set; }
        public string? pb_cover6_renew_custom_cover { get; set; }
        public string? pb_cover6_en_renew_custom_cover { get; set; }
        public string? pb_cover7_renew_mapping_type { get; set; }
        public string? pb_cover7_renew_field { get; set; }
        public string? pb_cover7_renew_custom_cover { get; set; }
        public string? pb_cover7_en_renew_custom_cover { get; set; }
        public string? pb_cover8_renew_mapping_type { get; set; }
        public string? pb_cover8_renew_field { get; set; }
        public string? pb_cover8_renew_custom_cover { get; set; }
        public string? pb_cover8_en_renew_custom_cover { get; set; }
        public string? pb_cover9_renew_mapping_type { get; set; }
        public string? pb_cover9_renew_field { get; set; }
        public string? pb_cover9_renew_custom_cover { get; set; }
        public string? pb_cover9_en_renew_custom_cover { get; set; }
        public string? pb_cover10_renew_mapping_type { get; set; }
        public string? pb_cover10_renew_field { get; set; }
        public string? pb_cover10_renew_custom_cover { get; set; }
        public string? pb_cover10_en_renew_custom_cover { get; set; }
        public string? pb_cover11_renew_mapping_type { get; set; }
        public string? pb_cover11_renew_field { get; set; }
        public string? pb_cover11_renew_custom_cover { get; set; }
        public string? pb_cover11_en_renew_custom_cover { get; set; }
        public string? pb_cover12_renew_mapping_type { get; set; }
        public string? pb_cover12_renew_field { get; set; }
        public string? pb_cover12_renew_custom_cover { get; set; }
        public string? pb_cover12_en_renew_custom_cover { get; set; }
        public string? pb_cover13_renew_mapping_type { get; set; }
        public string? pb_cover13_renew_field { get; set; }
        public string? pb_cover13_renew_custom_cover { get; set; }
        public string? pb_cover13_en_renew_custom_cover { get; set; }
        public string? pb_cover14_renew_mapping_type { get; set; }
        public string? pb_cover14_renew_field { get; set; }
        public string? pb_cover14_renew_custom_cover { get; set; }
        public string? pb_cover14_en_renew_custom_cover { get; set; }
        public string? pb_cover15_renew_mapping_type { get; set; }
        public string? pb_cover15_renew_field { get; set; }
        public string? pb_cover15_renew_custom_cover { get; set; }
        public string? pb_cover15_en_renew_custom_cover { get; set; }
        public string? pb_cover16_renew_mapping_type { get; set; }
        public string? pb_cover16_renew_field { get; set; }
        public string? pb_cover16_renew_custom_cover { get; set; }
        public string? pb_cover16_en_renew_custom_cover { get; set; }
        public string? pb_cover17_renew_mapping_type { get; set; }
        public string? pb_cover17_renew_field { get; set; }
        public string? pb_cover17_renew_custom_cover { get; set; }
        public string? pb_cover17_en_renew_custom_cover { get; set; }
        public string? pb_cover18_renew_mapping_type { get; set; }
        public string? pb_cover18_renew_field { get; set; }
        public string? pb_cover18_renew_custom_cover { get; set; }
        public string? pb_cover18_en_renew_custom_cover { get; set; }
        public string? pb_cover19_renew_mapping_type { get; set; }
        public string? pb_cover19_renew_field { get; set; }
        public string? pb_cover19_renew_custom_cover { get; set; }
        public string? pb_cover19_en_renew_custom_cover { get; set; }
        public string? pb_cover20_renew_mapping_type { get; set; }
        public string? pb_cover20_renew_field { get; set; }
        public string? pb_cover20_renew_custom_cover { get; set; }
        public string? pb_cover20_en_renew_custom_cover { get; set; }
    }
}